# Generated by Django 2.2.5 on 2019-09-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
