# Generated by Django 2.2.5 on 2019-10-01 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Prof', 'Prof'), ('Dr', 'Dr'), ('Lady', 'Lady'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Miss', 'Miss'), ('Mr', 'Mr'), ('Sir', 'Sir')], default='Mrs', max_length=4)),
                ('delivery_name', models.CharField(max_length=100)),
                ('street1', models.CharField(max_length=100)),
                ('street2', models.CharField(blank=True, max_length=100)),
                ('town', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Billing_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Prof', 'Prof'), ('Dr', 'Dr'), ('Lady', 'Lady'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Miss', 'Miss'), ('Mr', 'Mr'), ('Sir', 'Sir')], default='Mrs', max_length=4)),
                ('billing_name', models.CharField(max_length=80)),
                ('street1', models.CharField(max_length=100)),
                ('street2', models.CharField(blank=True, max_length=100)),
                ('town', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
