# Generated by Django 2.2.5 on 2019-09-19 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_name', models.CharField(max_length=200)),
                ('street1', models.CharField(max_length=200)),
                ('street2', models.CharField(max_length=200)),
                ('town', models.CharField(max_length=200)),
                ('county', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=200)),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('MR', 'Mr'), ('MRS', 'Mrs'), ('MS', 'Ms'), ('DR', 'Dr'), ('PROF', 'Prof')], default='MRS', max_length=4)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Billing_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_name', models.CharField(max_length=200)),
                ('street1', models.CharField(max_length=200)),
                ('street2', models.CharField(max_length=200)),
                ('town', models.CharField(max_length=200)),
                ('county', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=200)),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
