# Generated by Django 2.2.5 on 2019-09-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20190923_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_address',
            name='title',
            field=models.CharField(choices=[('Prof', 'Prof'), ('Dr', 'Dr'), ('Lady', 'Lady'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Miss', 'Miss'), ('Mr', 'Mr'), ('Sir', 'Sir')], default='Mrs', max_length=4),
        ),
    ]
