# Generated by Django 2.2.5 on 2019-09-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_delivery_address_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_address',
            name='street2',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
