# Generated by Django 2.2.5 on 2019-09-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20190924_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing_address',
            old_name='postcode',
            new_name='line5',
        ),
        migrations.RemoveField(
            model_name='billing_address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='billing_address',
            name='county',
        ),
        migrations.RemoveField(
            model_name='billing_address',
            name='street1',
        ),
        migrations.RemoveField(
            model_name='billing_address',
            name='street2',
        ),
        migrations.RemoveField(
            model_name='billing_address',
            name='town',
        ),
        migrations.AddField(
            model_name='billing_address',
            name='line1',
            field=models.CharField(default='fred', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing_address',
            name='line2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='billing_address',
            name='line3',
            field=models.CharField(default='tom', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing_address',
            name='line4',
            field=models.CharField(default='dick', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing_address',
            name='line6',
            field=models.CharField(default='harry', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billing_address',
            name='billing_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='delivery_address',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='delivery_address',
            name='county',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='delivery_address',
            name='delivery_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='delivery_address',
            name='street1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='delivery_address',
            name='street2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='delivery_address',
            name='town',
            field=models.CharField(max_length=50),
        ),
    ]
