# Generated by Django 2.2.5 on 2019-09-28 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20190925_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing_address',
            old_name='line3',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='billing_address',
            old_name='line4',
            new_name='county',
        ),
        migrations.RenameField(
            model_name='billing_address',
            old_name='line5',
            new_name='postcode',
        ),
        migrations.RenameField(
            model_name='billing_address',
            old_name='line1',
            new_name='street1',
        ),
        migrations.RenameField(
            model_name='billing_address',
            old_name='line2',
            new_name='street2',
        ),
        migrations.RenameField(
            model_name='billing_address',
            old_name='line6',
            new_name='town',
        ),
    ]
