# Generated by Django 2.2.5 on 2019-09-28 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20190928_1039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
