# Generated by Django 2.2.5 on 2019-09-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_address',
            name='title',
            field=models.CharField(choices=[('Prof', 'Prof'), ('Dr', 'Dr'), ('Lady', 'Lady'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Miss', 'Miss'), ('Mr', 'Mr'), ('Sir', 'Sir')], default='Mrs', max_length=4),
        ),
    ]
