# Generated by Django 2.2.5 on 2019-09-28 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_billing_address_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
