# Generated by Django 2.2.5 on 2019-09-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('sale_status', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('culture', models.CharField(default='', max_length=254)),
                ('era', models.CharField(default='', max_length=254)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
