# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-21 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('sale_status', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sale_in_one', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
