# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-21 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogue',
            name='sale_in_one',
        ),
    ]
