# Generated by Django 2.2.5 on 2019-09-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20190914_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
