# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-28 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_remove_catalogue_sale_in_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='culture',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='era',
            field=models.CharField(default='', max_length=254),
        ),
    ]
