# Generated by Django 2.2.5 on 2019-09-29 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='product',
            new_name='name',
        ),
    ]
