# Generated by Django 2.2.5 on 2019-09-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_catalogue_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='increment',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='reserve',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
