# Generated by Django 2.2.5 on 2019-09-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_auto_20190929_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogue',
            name='culture',
        ),
        migrations.RemoveField(
            model_name='catalogue',
            name='price',
        ),
        migrations.AddField(
            model_name='bid',
            name='product_ID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='name',
            field=models.CharField(default='', max_length=254),
        ),
    ]
