# Generated by Django 2.2.5 on 2019-09-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_auto_20190929_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='product_ID',
            field=models.IntegerField(null=True),
        ),
    ]
